innovare_user:
    resource: "@InnovareUserBundle/Controller/"
    type:     annotation
    prefix:   /

innovare_core:
    resource: "@InnovareCoreBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

_user_bundles:
    resource: '@InnovareUserBundle/Resources/config/routing.yml'
